# ==================================================================================================
# --- Dummy parameters ---
# ==================================================================================================
config_dummy:
  a: 2
  b: 10
  c: 256
