# ==================================================================================================
# --- Dummy parameters ---
# ==================================================================================================
some_ints:
  a: 2
  b: 10
  c: 4

a_float:
  d: 0.5
