# ==================================================================================================
# --- Dummy parameters ---
# ==================================================================================================
gen1:
  a: 2
  b: 10
  c: 4

gen2:
  d: 0.5
