# ==================================================================================================
# --- Dummy parameters ---
# ==================================================================================================
config_dummy:
  a: 2.0
  b: 10.0
  c: 256
