# ==================================================================================================
# --- Dummy parameters ---
# ==================================================================================================
some_ints:
  a: 2
  b: 10
  c: 4

a_float:
  d: 0.5

some_paths:
  path_fact_a_bc:
    value: "fact_a_bc.npy"
    internal_dependency: true
  path_result: "result.pkl"
